# The backup will be put in S3://BUCKET/DUMPS/MY_DATABASE-TIMESTAMP.sql.gz
 bucket: bucket
 folder: dumps
 AWS_ACCESS_KEY_ID: 00000000000000000000
 AWS_SECRET_ACCESS_KEY: 0000000000000000000000000000000000000000
 email: email@example.com
 smtp_server: localhost
 hostname: example.com
 mysql_user: user
 mysql_password: pass